name: volt_market
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ^3.7.2



#----------------------- packages -------------------------#
dependencies:
  flutter:
    sdk: flutter

# Utility Packages
  get: ^4.7.2
  flutter_native_splash: ^2.4.6
  supabase_flutter: ^2.8.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  get_it: ^8.0.3
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  bloc: ^9.0.0
  image_picker: ^1.1.2
  path: ^1.9.1
  mime: ^2.0.0
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.2.3
  local_auth: ^2.0.0
# Icons  
  cupertino_icons: ^1.0.8
  iconsax_flutter: ^1.0.0
  



#----------------------./ Packages End --------------------#


dev_dependencies:
  flutter_test:
    sdk: flutter 

  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

#---------------------- Local Assets ----------------------#
  assets:
    - assets/svgs/
    - assets/images/

  
#---------------------- Local Fonts ----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
    
    
    
    
    
  
  
  
