// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7MSIC_XnKz6nHH2B4VkeUwoa5UPuZfo',
    appId: '1:313738691943:web:7136459b38cb5704539bc2',
    messagingSenderId: '313738691943',
    projectId: 'voltmarket-50efe',
    authDomain: 'voltmarket-50efe.firebaseapp.com',
    storageBucket: 'voltmarket-50efe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLl6tShLgGJLqwUJmzdIO0DIsLYiX26k',
    appId: '1:313738691943:android:6b3b60cc8abf414f539bc2',
    messagingSenderId: '313738691943',
    projectId: 'voltmarket-50efe',
    storageBucket: 'voltmarket-50efe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_h9lrNBW2IHg5ISJXdX6WZX6z3gYzRwE',
    appId: '1:313738691943:ios:0d378e157be1a6a9539bc2',
    messagingSenderId: '313738691943',
    projectId: 'voltmarket-50efe',
    storageBucket: 'voltmarket-50efe.firebasestorage.app',
    iosBundleId: 'com.example.voltMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_h9lrNBW2IHg5ISJXdX6WZX6z3gYzRwE',
    appId: '1:313738691943:ios:0d378e157be1a6a9539bc2',
    messagingSenderId: '313738691943',
    projectId: 'voltmarket-50efe',
    storageBucket: 'voltmarket-50efe.firebasestorage.app',
    iosBundleId: 'com.example.voltMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz7MSIC_XnKz6nHH2B4VkeUwoa5UPuZfo',
    appId: '1:313738691943:web:f84694cd1b373199539bc2',
    messagingSenderId: '313738691943',
    projectId: 'voltmarket-50efe',
    authDomain: 'voltmarket-50efe.firebaseapp.com',
    storageBucket: 'voltmarket-50efe.firebasestorage.app',
  );
}
