import 'package:flutter/material.dart';

List<DropdownMenuItem<String>> governorateItems = [
  DropdownMenuItem(value: 'Cairo', child: Text('Cairo')),
  DropdownMenuItem(value: 'Giza', child: Text('Giza')),
  DropdownMenuItem(value: 'Alexandria', child: Text('Alexandria')),
  DropdownMenuItem(value: 'Qalyubia', child: Text('Qalyubia')),
  DropdownMenuItem(value: 'Daqahlia', child: Text('Daqahlia')),
  DropdownMenuItem(value: 'Sharqia', child: Text('Sharqia')),
  DropdownMenuItem(value: 'Gharbia', child: Text('Gharbia')),
  DropdownMenuItem(value: 'Beheira', child: Text('Beheira')),
  DropdownMenuItem(value: 'Kafr El Sheikh', child: Text('Kafr El Sheikh')),
  DropdownMenuItem(value: 'Monufia', child: Text('Monufia')),
  DropdownMenuItem(value: 'Fayoum', child: Text('Fayoum')),
  DropdownMenuItem(value: 'Beni Suef', child: Text('Beni Suef')),
  DropdownMenuItem(value: 'Minya', child: Text('Minya')),
  DropdownMenuItem(value: 'Assiut', child: Text('Assiut')),
  DropdownMenuItem(value: 'Sohag', child: Text('Sohag')),
  DropdownMenuItem(value: 'Qena', child: Text('Qena')),
  DropdownMenuItem(value: 'Luxor', child: Text('Luxor')),
  DropdownMenuItem(value: 'Aswan', child: Text('Aswan')),
  DropdownMenuItem(value: 'Red Sea', child: Text('Red Sea')),
  DropdownMenuItem(value: 'New Valley', child: Text('New Valley')),
  DropdownMenuItem(value: 'Matrouh', child: Text('Matrouh')),
  DropdownMenuItem(value: 'North Sinai', child: Text('North Sinai')),
  DropdownMenuItem(value: 'South Sinai', child: Text('South Sinai')),
  DropdownMenuItem(value: 'Damietta', child: Text('Damietta')),
  DropdownMenuItem(value: 'Port Said', child: Text('Port Said')),
  DropdownMenuItem(value: 'Ismailia', child: Text('Ismailia')),
  DropdownMenuItem(value: 'Suez', child: Text('Suez')),
];